 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tetetetes", type: :request do
  
  # Tetetete. As you add validations to Tetetete, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tetetete.create! valid_attributes
      get tetetetes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tetetete = Tetetete.create! valid_attributes
      get tetetete_url(tetetete)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tetetete_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tetetete = Tetetete.create! valid_attributes
      get edit_tetetete_url(tetetete)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tetetete" do
        expect {
          post tetetetes_url, params: { tetetete: valid_attributes }
        }.to change(Tetetete, :count).by(1)
      end

      it "redirects to the created tetetete" do
        post tetetetes_url, params: { tetetete: valid_attributes }
        expect(response).to redirect_to(tetetete_url(Tetetete.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tetetete" do
        expect {
          post tetetetes_url, params: { tetetete: invalid_attributes }
        }.to change(Tetetete, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tetetetes_url, params: { tetetete: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tetetete" do
        tetetete = Tetetete.create! valid_attributes
        patch tetetete_url(tetetete), params: { tetetete: new_attributes }
        tetetete.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tetetete" do
        tetetete = Tetetete.create! valid_attributes
        patch tetetete_url(tetetete), params: { tetetete: new_attributes }
        tetetete.reload
        expect(response).to redirect_to(tetetete_url(tetetete))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tetetete = Tetetete.create! valid_attributes
        patch tetetete_url(tetetete), params: { tetetete: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tetetete" do
      tetetete = Tetetete.create! valid_attributes
      expect {
        delete tetetete_url(tetetete)
      }.to change(Tetetete, :count).by(-1)
    end

    it "redirects to the tetetetes list" do
      tetetete = Tetetete.create! valid_attributes
      delete tetetete_url(tetetete)
      expect(response).to redirect_to(tetetetes_url)
    end
  end
end
